# Generated by Django 4.1.4 on 2022-12-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarow',
            old_name='document',
            new_name='data',
        ),
        migrations.CreateModel(
            name='CleanedDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.data')),
            ],
        ),
    ]
