# Generated by Django 4.1.4 on 2022-12-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_document_datarow_data_cleaneddatarow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarow',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='clean_file',
            field=models.FileField(null=True, upload_to='clean_data/'),
        ),
        migrations.AddField(
            model_name='data',
            name='raw_file',
            field=models.FileField(null=True, upload_to='raw_data/'),
        ),
        migrations.DeleteModel(
            name='CleanedDataRow',
        ),
        migrations.DeleteModel(
            name='DataRow',
        ),
    ]
