# Generated by Django 4.1.4 on 2022-12-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_datarow_data_data_clean_file_data_raw_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='text_column',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(default='Untitled', max_length=255, unique=True),
        ),
    ]
